## Joint Kinematics Sandbox

In [2]:
import numpy as np

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
d = np.array([3, 3, 4])
d = np.array([d])
d.T

array([[3],
       [3],
       [4]])

In [11]:
arr = np.array([1, 2, 3])
np.append(arr, 3)

array([1, 2, 3, 3])

In [13]:
a = np.eye(3)
b = a
b = np.eye(4)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.array([1, 2, 3]).tolist()

[1, 2, 3]

In [5]:
c1 = np.array([[1, 2, 3]]).T
c2 = np.array([[1, 2, 3]]).T
np.hstack([c1, c2])

array([[1, 1],
       [2, 2],
       [3, 3]])