## Joint Kinematics Sandbox

In [6]:
import numpy as np

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
d = np.array([3, 3, 4])
d = np.array([d])
d.T

array([[3],
       [3],
       [4]])

In [11]:
arr = np.array([1, 2, 3])
np.append(arr, 3)

array([1, 2, 3, 3])

In [13]:
a = np.eye(3)
b = a
b = np.eye(4)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.array([1, 2, 3]).tolist()

[1, 2, 3]

In [5]:
c1 = np.array([[1, 2, 3]]).T
c2 = np.array([[1, 2, 3]]).T
np.hstack([c1, c2])

array([[1, 1],
       [2, 2],
       [3, 3]])

In [18]:
a = [1, 2, 3, 4]
wrt = -1
if wrt == -1:
    wrt = len(a)-1
a[:wrt+1]

[1, 2, 3, 4]

In [21]:
np.zeros((5, 1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [24]:
v = [2, 3, 4, 5]
v = np.array([v]).T
v

array([[2],
       [3],
       [4],
       [5]])

In [6]:
d = {1: 'hi'}
0 in d

False

In [7]:
l = [1, 2, 3]
l.insert(0, 0.5)
l

[0.5, 1, 2, 3]

In [10]:
l = [[1, 2], [2, 3], [4, 5]]
for n in l:
    n[0] = 3

l

[[3, 2], [3, 3], [3, 5]]

In [11]:
'k'.upper()

'K'

In [12]:
l = [1, 2, 3]
l[:1]

[1]

In [23]:
import numpy as np
int(np.round(0.51, 0))

1

In [24]:
int((2.5, 2.4, 2.4))

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'tuple'